using System.Collections.Generic;
using System.Globalization;
// ReSharper disable StringLiteralTypo

namespace BricksBucket.Localization.Standardization
{
	// LCID Part.
	// By Javier García | @jvrgms | 2020
	public static partial class Standards
	{
		/// <summary>
		/// Gets the name of the given LCID enum value.
		/// </summary>
		/// <param name="lcid">LCID to look for its name.</param>
		/// <returns>Empty if the LCID value has not a name.</returns>
		public static string GetName (Lcid lcid) =>
			LcidNames.ContainsKey (lcid) ? LcidNames[lcid] : string.Empty;

		/// <summary>
		/// Gets the code of the given LCID enum value.
		/// </summary>
		/// <param name="lcid">LCID to look for its code.</param>
		/// <returns>Empty if the LCID value has not a code.</returns>
		public static string GetCode (Lcid lcid) =>
			LcidCodes.ContainsKey (lcid) ? LcidCodes[lcid] : string.Empty;

		/// <summary>
		/// Gets the LCID enum value for the given string code.
		/// </summary>
		/// <param name="code">String value of the code of an LCID.</param>
		/// <returns><value>Lcid.INVARIANT</value> if the code is an string
		/// empty,<value>Lcid.NONE</value> if a code is not found.</returns>
		public static Lcid GetLcid (string code)
		{
			var value = code.Replace ("-", "_");
			return System.Enum.TryParse (value, ignoreCase: true, out Lcid lcid)
				? lcid
				: string.IsNullOrEmpty (code)
					? Lcid.INVARIANT
					: LcidAliases.ContainsKey (code)
						? LcidAliases[code]
						: Lcid.NONE;
		}

		/// <summary>
		/// Gets the LCID enum value for the given language, region and script.
		/// </summary>
		/// <param name="language">ISO 639 code.</param>
		/// <param name="region">Optional UN.M49 code.</param>
		/// <param name="script">Optional ISO 15924 code.</param>
		/// <param name="ext">Optional extra tag.</param>
		/// <returns><value>Lcid.NONE</value> for not found LCID codes.
		/// </returns>
		public static Lcid GetLcid (
			Iso639 language, Unm49 region = Unm49.NONE,
			Iso15924 script = Iso15924.NONE, string ext = ""
		)
		{
			if (language == Iso639.NONE) return Lcid.NONE;

			var builder = new System.Text.StringBuilder ();
			builder.Append (language.ToString ());

			if (script != Iso15924.NONE)
			{
				builder.Append ("_");
				builder.Append (script.ToString ());
			}

			if (region != Unm49.NONE)
			{
				builder.Append ("_");
				var iso3166 = GetIso3166 (region);
				builder.Append (iso3166 == Iso3166.NONE
					? GetCode (region)
					: iso3166.ToString ());
			}

			// ReSharper disable once InvertIf
			if (ext != string.Empty)
			{
				builder.Append ("_");
				builder.Append (ext);
			}

			return GetLcid (builder.ToString ());
		}
		
		/// <summary>
		/// Gets the ISO 639 code of an LCID.
		/// </summary>
		/// <param name="lcid">LCID to look for its ISO 639 code.</param>
		/// <returns><value>Iso639.NONE</value> for a LCID not found.</returns>
		public static Iso639 GetIso639 (Lcid lcid) =>
			LcidLanguages.ContainsKey (lcid)
				? LcidLanguages[lcid]
				: Iso639.NONE;

		/// <summary>
		/// Gets the UN M49 code of an LCID.
		/// </summary>
		/// <param name="lcid">LCID to look for its UN M49 code.</param>
		/// <returns><value>Unm49.NONE</value> for a LCID not found.</returns>
		public static Unm49 GetUnm49 (Lcid lcid) =>
			LcidRegions.ContainsKey (lcid)
				? LcidRegions[lcid]
				: GetUnm49 (GetIso3166 (lcid));
		
		/// <summary>
		/// Gets the ISO 3166 code of an LCID.
		/// </summary>
		/// <param name="lcid">LCID to look for its ISO 3166 code.</param>
		/// <returns><value>Iso3166.NONE</value> for a LCID not found.</returns>
		public static Iso3166 GetIso3166 (Lcid lcid) =>
			LcidCountries.ContainsKey (lcid)
				? LcidCountries[lcid]
				: Iso3166.NONE;

		/// <summary>
		/// Gets the <b>CultureInfo</b> of an LCID.
		/// </summary>
		/// <param name="lcid">LCID to look for its CultureInfo.</param>
		/// <returns><value>Null</value> for a LCID not found.</returns>
		public static CultureInfo GetCultureInfo (Lcid lcid) =>
			System.Enum.IsDefined (typeof (Lcid), lcid) && lcid != Lcid.NONE
				? lcid == Lcid.INVARIANT
					? CultureInfo.InvariantCulture 
					: CultureInfo.GetCultureInfo ((int) lcid)
				: null;

		/// <summary>
		/// Dictionary of the names for LCID enum members.
		/// </summary>
		private static readonly Dictionary<Lcid, string> LcidNames =
			new Dictionary<Lcid, string>
			{
				{Lcid.NONE, "None"},
				{Lcid.INVARIANT, "Invariant Language (Invariant Country)"},
				{Lcid.AF, "Afrikaans"},
				{Lcid.AF_ZA, "Afrikaans - South Africa"},
				{Lcid.AM, "Amharic"},
				{Lcid.AM_ET, "Amharic - Ethiopia"},
				{Lcid.AR, "Arabic"},
				{Lcid.AR_AE, "Arabic - United Arab Emirates"},
				{Lcid.AR_BH, "Arabic - Bahrain"},
				{Lcid.AR_DZ, "Arabic - Algeria"},
				{Lcid.AR_EG, "Arabic - Egypt"},
				{Lcid.AR_IQ, "Arabic - Iraq"},
				{Lcid.AR_JO, "Arabic - Jordan"},
				{Lcid.AR_KW, "Arabic - Kuwait"},
				{Lcid.AR_LB, "Arabic - Lebanon"},
				{Lcid.AR_LY, "Arabic - Libya"},
				{Lcid.AR_MA, "Arabic - Morocco"},
				{Lcid.AR_OM, "Arabic - Oman"},
				{Lcid.AR_QA, "Arabic - Qatar"},
				{Lcid.AR_SA, "Arabic - Saudi Arabia"},
				{Lcid.AR_SY, "Arabic - Syrian Arab Republic"},
				{Lcid.AR_TN, "Arabic - Tunisia"},
				{Lcid.AR_YE, "Arabic - Yemen"},
				{Lcid.AS, "Assamese"},
				{Lcid.AS_IN, "Assamese - India"},
				{Lcid.AZ, "Azerbaijani"},
				{Lcid.AZ_CYRL, "Azerbaijani (Cyrillic)"},
				{Lcid.AZ_CYRL_AZ, "Azerbaijani - Azerbaijan (Cyrillic)"},
				{Lcid.AZ_LATN, "Azerbaijani (Latin)"},
				{Lcid.AZ_LATN_AZ, "Azerbaijani - Azerbaijan (Latin)"},
				{Lcid.BE, "Belarusian"},
				{Lcid.BE_BY, "Belarusian - Belarus"},
				{Lcid.BG, "Bulgarian"},
				{Lcid.BG_BG, "Bulgarian - Bulgaria"},
				{Lcid.BN, "Bengali"},
				{Lcid.BN_BD, "Bengali - Bangladesh"},
				{Lcid.BN_IN, "Bengali - India"},
				{Lcid.BO, "Tibetan"},
				{Lcid.BO_CN, "Tibetan - China"},
				{Lcid.BR, "Breton"},
				{Lcid.BR_FR, "Breton - France"},
				{Lcid.BS, "Bosnian"},
				{Lcid.BS_CYRL, "Bosnian (Cyrillic)"},
				{
					Lcid.BS_CYRL_BA,
					"Bosnian - Bosnia and Herzegovina (Cyrillic)"
				},
				{Lcid.BS_LATN, "Bosnian (Latin)"},
				{
					Lcid.BS_LATN_BA,
					"Bosnian - Bosnia and Herzegovina (Latin)"
				},
				{Lcid.CA, "Catalan"},
				{Lcid.CA_ES, "Catalan - Spain"},
				{Lcid.CA_ES_VALENCIA, "Catalan - Spain (Valencia)"},
				{Lcid.CHR, "Cherokee"},
				{Lcid.CS, "Czech"},
				{Lcid.CS_CZ, "Czech - Czechia"},
				{Lcid.CY, "Welsh"},
				{
					Lcid.CY_GB,
					"Welsh - United Kingdom of Great Britain and Northern" +
					"Ireland"
				},
				{Lcid.DA, "Danish"},
				{Lcid.DA_DK, "Danish - Denmark"},
				{Lcid.DE, "German"},
				{Lcid.DE_AT, "German - Austria"},
				{Lcid.DE_CH, "German - Switzerland"},
				{Lcid.DE_DE, "German - Germany"},
				{Lcid.DE_LI, "German - Liechtenstein"},
				{Lcid.DE_LU, "German - Luxembourg"},
				{Lcid.DSB, "Lower Sorbian"},
				{Lcid.DSB_DE, "Lower Sorbian - Germany"},
				{Lcid.EL, "Greek"},
				{Lcid.EL_GR, "Greek - Greece"},
				{Lcid.EN, "English"},
				{Lcid.EN_AU, "English - Australia"},
				{Lcid.EN_BZ, "English - Belize"},
				{Lcid.EN_CA, "English - Canada"},
				{
					Lcid.EN_GB,
					"English - United Kingdom of Great Britain and Northern" +
					"Ireland"
				},
				{Lcid.EN_HK, "English - Hong Kong"},
				{Lcid.EN_IE, "English - Ireland"},
				{Lcid.EN_IN, "English - India"},
				{Lcid.EN_JM, "English - Jamaica"},
				{Lcid.EN_MY, "English - Malaysia"},
				{Lcid.EN_NZ, "English - New Zealand"},
				{Lcid.EN_PH, "English - Philippines"},
				{Lcid.EN_SG, "English - Singapore"},
				{Lcid.EN_TT, "English - Trinidad and Tobago"},
				{Lcid.EN_US, "English - United States of America"},
				{Lcid.EN_ZA, "English - South Africa"},
				{Lcid.EN_ZW, "English - Zimbabwe"},
				{Lcid.ES, "Spanish"},
				{Lcid.ES_AR, "Spanish - Argentina"},
				{Lcid.ES_BO, "Spanish - Bolivia, Plurinational State of"},
				{Lcid.ES_CL, "Spanish - Chile"},
				{Lcid.ES_CO, "Spanish - Colombia"},
				{Lcid.ES_CR, "Spanish - Costa Rica"},
				{Lcid.ES_CU, "Spanish - Cuba"},
				{Lcid.ES_DO, "Spanish - Dominican Republic"},
				{Lcid.ES_EC, "Spanish - Ecuador"},
				{Lcid.ES_ES, "Spanish - Spain"},
				{Lcid.ES_GT, "Spanish - Guatemala"},
				{Lcid.ES_HN, "Spanish - Honduras"},
				{Lcid.ES_MX, "Spanish - Mexico"},
				{Lcid.ES_NI, "Spanish - Nicaragua"},
				{Lcid.ES_PA, "Spanish - Panama"},
				{Lcid.ES_PE, "Spanish - Peru"},
				{Lcid.ES_PR, "Spanish - Puerto Rico"},
				{Lcid.ES_PY, "Spanish - Paraguay"},
				{Lcid.ES_SV, "Spanish - El Salvador"},
				{Lcid.ES_US, "Spanish - United States of America"},
				{Lcid.ES_UY, "Spanish - Uruguay"},
				{
					Lcid.ES_VE,
					"Spanish - Venezuela (Bolivarian Republic of)"
				},
				{Lcid.ET, "Estonian"},
				{Lcid.ET_EE, "Estonian - Estonia"},
				{Lcid.EU, "Basque"},
				{Lcid.EU_ES, "Basque - Spain"},
				{Lcid.FA, "Persian"},
				{Lcid.FA_IR, "Persian - Iran (Islamic Republic of)"},
				{Lcid.FF, "Fulah"},
				{Lcid.FI, "Finnish"},
				{Lcid.FI_FI, "Finnish - Finland"},
				{Lcid.FIL, "Filipino"},
				{Lcid.FIL_PH, "Filipino - Philippines"},
				{Lcid.FO, "Faroese"},
				{Lcid.FO_FO, "Faroese - Faroe Islands"},
				{Lcid.FR, "French"},
				{Lcid.FR_BE, "French - Belgium"},
				{Lcid.FR_CA, "French - Canada"},
				{Lcid.FR_CD, "French - Congo, Democratic Republic of the"},
				{Lcid.FR_CH, "French - Switzerland"},
				{Lcid.FR_CI, "French - Côte d'Ivoire"},
				{Lcid.FR_CM, "French - Cameroon"},
				{Lcid.FR_FR, "French - France"},
				{Lcid.FR_HT, "French - Haiti"},
				{Lcid.FR_LU, "French - Luxembourg"},
				{Lcid.FR_MA, "French - Morocco"},
				{Lcid.FR_MC, "French - Monaco"},
				{Lcid.FR_ML, "French - Mali"},
				{Lcid.FR_RE, "French - Réunion"},
				{Lcid.FR_SN, "French - Senegal"},
				{Lcid.FY, "Western Frisian"},
				{Lcid.FY_NL, "Western Frisian - Netherlands"},
				{Lcid.GA, "Irish"},
				{Lcid.GA_IE, "Irish - Ireland"},
				{Lcid.GD, "Scottish Gaelic"},
				{
					Lcid.GD_GB,
					"Scottish Gaelic - United Kingdom of Great Britain and" +
					"Northern Ireland"
				},
				{Lcid.GL, "Galician"},
				{Lcid.GL_ES, "Galician - Spain"},
				{Lcid.GSW, "Alsatian"},
				{Lcid.GSW_FR, "Alsatian - France"},
				{Lcid.GU, "Gujarati"},
				{Lcid.GU_IN, "Gujarati - India"},
				{Lcid.HA, "Hausa"},
				{Lcid.HA_LATN, "Hausa (Latin)"},
				{Lcid.HA_LATN_NG, "Hausa - Nigeria (Latin)"},
				{Lcid.HAW, "Hawaiian"},
				{Lcid.HAW_US, "Hawaiian - United States of America"},
				{Lcid.HE, "Hebrew"},
				{Lcid.HE_IL, "Hebrew - Israel"},
				{Lcid.HI, "Hindi"},
				{Lcid.HI_IN, "Hindi - India"},
				{Lcid.HR_BA, "Croatian - Bosnia and Herzegovina"},
				{Lcid.HR_HR, "Croatian - Croatia"},
				{Lcid.HR, "Croatian"},
				{Lcid.HSB, "Upper Sorbian"},
				{Lcid.HSB_DE, "Upper Sorbian - Germany"},
				{Lcid.HU, "Hungarian"},
				{Lcid.HU_HU, "Hungarian - Hungary"},
				{Lcid.HY, "Armenian"},
				{Lcid.HY_AM, "Armenian - Armenia"},
				{Lcid.ID, "Indonesian"},
				{Lcid.ID_ID, "Indonesian - Indonesia"},
				{Lcid.IG, "Igbo"},
				{Lcid.IG_NG, "Igbo - Nigeria"},
				{Lcid.II, "Yi"},
				{Lcid.II_CN, "Yi - China"},
				{Lcid.IS, "Icelandic"},
				{Lcid.IS_IS, "Icelandic - Iceland"},
				{Lcid.IT, "Italian"},
				{Lcid.IT_CH, "Italian - Switzerland"},
				{Lcid.IT_IT, "Italian - Italy"},
				{Lcid.JA, "Japanese"},
				{Lcid.JA_JP, "Japanese - Japan"},
				{Lcid.KA, "Georgian"},
				{Lcid.KA_GE, "Georgian - Georgia"},
				{Lcid.KK, "Kazakh"},
				{Lcid.KK_KZ, "Kazakh - Kazakhstan"},
				{Lcid.KL, "Greenlandic"},
				{Lcid.KL_GL, "Greenlandic - Greenland"},
				{Lcid.KM, "Khmer"},
				{Lcid.KM_KH, "Khmer - Cambodia"},
				{Lcid.KN, "Kannada"},
				{Lcid.KN_IN, "Kannada - India"},
				{Lcid.KO, "Korean"},
				{Lcid.KO_KR, "Korean - Korea, Republic of"},
				{Lcid.KOK, "Konkani"},
				{Lcid.KOK_IN, "Konkani - India"},
				{Lcid.KY, "Kyrgyz"},
				{Lcid.KY_KG, "Kyrgyz - Kyrgyzstan"},
				{Lcid.LB, "Luxembourgish"},
				{Lcid.LB_LU, "Luxembourgish - Luxembourg"},
				{Lcid.LO, "Lao"},
				{Lcid.LO_LA, "Lao - Lao People's Democratic Republic"},
				{Lcid.LT, "Lithuanian"},
				{Lcid.LT_LT, "Lithuanian - Lithuania"},
				{Lcid.LV, "Latvian"},
				{Lcid.LV_LV, "Latvian - Latvia"},
				{Lcid.MK, "Macedonian"},
				{Lcid.MK_MK, "Macedonian - North Macedonia"},
				{Lcid.ML, "Malayalam"},
				{Lcid.ML_IN, "Malayalam - India"},
				{Lcid.MN, "Mongolian"},
				{Lcid.MN_CYRL, "Mongolian (Cyrillic)"},
				{Lcid.MN_MN, "Mongolian - Mongolia"},
				{Lcid.MR, "Marathi"},
				{Lcid.MR_IN, "Marathi - India"},
				{Lcid.MS, "Malay"},
				{Lcid.MS_BN, "Malay - Brunei Darussalam"},
				{Lcid.MS_MY, "Malay - Malaysia"},
				{Lcid.MT, "Maltese"},
				{Lcid.MT_MT, "Maltese - Malta"},
				{Lcid.MY, "Burmese"},
				{Lcid.MY_MM, "Burmese - Myanmar"},
				{Lcid.NB, "Norwegian Bokmål"},
				{Lcid.NB_NO, "Norwegian Bokmål - Norway"},
				{Lcid.NE, "Nepali"},
				{Lcid.NE_IN, "Nepali - India"},
				{Lcid.NE_NP, "Nepali - Nepal"},
				{Lcid.NL, "Dutch"},
				{Lcid.NL_BE, "Dutch - Belgium"},
				{Lcid.NL_NL, "Dutch - Netherlands"},
				{Lcid.NN, "Norwegian Nynorsk"},
				{Lcid.NN_NO, "Norwegian Nynorsk - Norway"},
				{Lcid.NO, "Norwegian"},
				{Lcid.NSO, "Sesotho sa Leboa"},
				{Lcid.NSO_ZA, "Sesotho sa Leboa - South Africa"},
				{Lcid.OM, "Oromo"},
				{Lcid.OM_ET, "Oromo - Ethiopia"},
				{Lcid.OR, "Odia"},
				{Lcid.OR_IN, "Odia - India"},
				{Lcid.PA, "Punjabi"},
				{Lcid.PA_ARAB, "Punjabi (Arabic)"},
				{Lcid.PA_ARAB_PK, "Punjabi - Pakistan (Arabic)"},
				{Lcid.PL, "Polish"},
				{Lcid.PL_PL, "Polish - Poland"},
				{Lcid.PS, "Pashto"},
				{Lcid.PS_AF, "Pashto - Afghanistan"},
				{Lcid.PT, "Portuguese"},
				{Lcid.PT_BR, "Portuguese - Brazil"},
				{Lcid.PT_PT, "Portuguese - Portugal"},
				{Lcid.RM, "Romansh"},
				{Lcid.RM_CH, "Romansh - Switzerland"},
				{Lcid.RO, "Romanian"},
				{Lcid.RO_MD, "Romanian - Moldova, Republic of"},
				{Lcid.RO_RO, "Romanian - Romania"},
				{Lcid.RU, "Russian"},
				{Lcid.RU_MD, "Russian - Moldova, Republic of"},
				{Lcid.RU_RU, "Russian - Russian Federation"},
				{Lcid.RW, "Kinyarwanda"},
				{Lcid.RW_RW, "Kinyarwanda - Rwanda"},
				{Lcid.SAH, "Sakha"},
				{Lcid.SAH_RU, "Sakha - Russian Federation"},
				{Lcid.SE, "Northern Sami"},
				{Lcid.SE_FI, "Northern Sami - Finland"},
				{Lcid.SE_NO, "Northern Sami - Norway"},
				{Lcid.SE_SE, "Northern Sami - Sweden"},
				{Lcid.SI, "Sinhala"},
				{Lcid.SI_LK, "Sinhala - Sri Lanka"},
				{Lcid.SK, "Slovak"},
				{Lcid.SK_SK, "Slovak - Slovakia"},
				{Lcid.SL, "Slovenian"},
				{Lcid.SL_SI, "Slovenian - Slovenia"},
				{Lcid.SMN, "Sami Inari"},
				{Lcid.SMN_FI, "Sami Inari - Finland"},
				{Lcid.SO, "Somali"},
				{Lcid.SO_SO, "Somali - Somalia"},
				{Lcid.SQ, "Albanian"},
				{Lcid.SQ_AL, "Albanian - Albania"},
				{Lcid.SR, "Serbian"},
				{Lcid.SR_CYRL, "Serbian (Cyrillic)"},
				{
					Lcid.SR_CYRL_BA,
					"Serbian - Bosnia and Herzegovina (Cyrillic)"
				},
				{Lcid.SR_CYRL_ME, "Serbian - Montenegro (Cyrillic)"},
				{Lcid.SR_CYRL_RS, "Serbian - Serbia (Cyrillic)"},
				{Lcid.SR_LATN, "Serbian (Latin)"},
				{
					Lcid.SR_LATN_BA,
					"Serbian - Bosnia and Herzegovina (Latin)"
				},
				{Lcid.SR_LATN_ME, "Serbian - Montenegro (Latin)"},
				{Lcid.SR_LATN_RS, "Serbian - Serbia (Latin)"},
				{Lcid.ST, "Sotho"},
				{Lcid.ST_ZA, "Sotho - South Africa"},
				{Lcid.SV, "Swedish"},
				{Lcid.SV_FI, "Swedish - Finland"},
				{Lcid.SV_SE, "Swedish - Sweden"},
				{Lcid.SW, "Swahili"},
				{Lcid.SW_KE, "Swahili - Kenya"},
				{Lcid.TA, "Tamil"},
				{Lcid.TA_IN, "Tamil - India"},
				{Lcid.TA_LK, "Tamil - Sri Lanka"},
				{Lcid.TE, "Telugu"},
				{Lcid.TE_IN, "Telugu - India"},
				{Lcid.TG, "Tajik"},
				{Lcid.TG_CYRL, "Tajik (Cyrillic)"},
				{Lcid.TG_CYRL_TJ, "Tajik - Tajikistan (Cyrillic)"},
				{Lcid.TH, "Thai"},
				{Lcid.TH_TH, "Thai - Thailand"},
				{Lcid.TI, "Tigrinya"},
				{Lcid.TI_ER, "Tigrinya - Eritrea"},
				{Lcid.TI_ET, "Tigrinya - Ethiopia"},
				{Lcid.TK, "Turkmen"},
				{Lcid.TK_TM, "Turkmen - Turkmenistan"},
				{Lcid.TN, "Tswana"},
				{Lcid.TN_BW, "Tswana - Botswana"},
				{Lcid.TN_ZA, "Tswana - South Africa"},
				{Lcid.TR, "Turkish"},
				{Lcid.TR_TR, "Turkish - Turkey"},
				{Lcid.TS, "Tsonga"},
				{Lcid.TS_ZA, "Tsonga - South Africa"},
				{Lcid.TZM, "Tamazight"},
				{Lcid.TZM_LATN, "Tamazight (Latin)"},
				{Lcid.UG, "Uyghur"},
				{Lcid.UG_CN, "Uyghur - China"},
				{Lcid.UK, "Ukrainian"},
				{Lcid.UK_UA, "Ukrainian - Ukraine"},
				{Lcid.UR, "Urdu"},
				{Lcid.UR_IN, "Urdu - India"},
				{Lcid.UR_PK, "Urdu - Pakistan"},
				{Lcid.UZ, "Uzbek"},
				{Lcid.UZ_CYRL, "Uzbek (Cyrillic)"},
				{Lcid.UZ_CYRL_UZ, "Uzbek - Uzbekistan (Cyrillic)"},
				{Lcid.UZ_LATN, "Uzbek (Latin)"},
				{Lcid.UZ_LATN_UZ, "Uzbek - Uzbekistan (Latin)"},
				{Lcid.VI, "Vietnamese"},
				{Lcid.VI_VN, "Vietnamese - Viet Nam"},
				{Lcid.XH, "Xhosa"},
				{Lcid.XH_ZA, "Xhosa - South Africa"},
				{Lcid.YO, "Yoruba"},
				{Lcid.YO_NG, "Yoruba - Nigeria"},
				{Lcid.ZH, "Chinese"},
				{Lcid.ZH_CN, "Chinese - China"},
				{Lcid.ZH_HANS, "Chinese (Han Simplified)"},
				{Lcid.ZH_HANT, "Chinese (Han Traditional)"},
				{Lcid.ZH_HK, "Chinese - Hong Kong"},
				{Lcid.ZH_MO, "Chinese - Macao"},
				{Lcid.ZH_SG, "Chinese - Singapore"},
				{Lcid.ZH_TW, "Chinese - Taiwan, Province of China"},
				{Lcid.ZU, "Zulu"},
				{Lcid.ZU_ZA, "Zulu - South Africa"},
			};

		/// <summary>
		/// Dictionary of the codes for LCID enum members.
		/// </summary>
		private static readonly Dictionary<Lcid, string> LcidCodes =
			new Dictionary<Lcid, string>
			{
				{Lcid.NONE, "none"},
				{Lcid.INVARIANT, "invariant"},
				{Lcid.AF, "af"},
				{Lcid.AF_ZA, "af-ZA"},
				{Lcid.AM, "am"},
				{Lcid.AM_ET, "am-ET"},
				{Lcid.AR, "ar"},
				{Lcid.AR_AE, "ar-AE"},
				{Lcid.AR_BH, "ar-BH"},
				{Lcid.AR_DZ, "ar-DZ"},
				{Lcid.AR_EG, "ar-EG"},
				{Lcid.AR_IQ, "ar-IQ"},
				{Lcid.AR_JO, "ar-JO"},
				{Lcid.AR_KW, "ar-KW"},
				{Lcid.AR_LB, "ar-LB"},
				{Lcid.AR_LY, "ar-LY"},
				{Lcid.AR_MA, "ar-MA"},
				{Lcid.AR_OM, "ar-OM"},
				{Lcid.AR_QA, "ar-QA"},
				{Lcid.AR_SA, "ar-SA"},
				{Lcid.AR_SY, "ar-SY"},
				{Lcid.AR_TN, "ar-TN"},
				{Lcid.AR_YE, "ar-YE"},
				{Lcid.AS, "as"},
				{Lcid.AS_IN, "as-IN"},
				{Lcid.AZ, "az"},
				{Lcid.AZ_CYRL, "az-Cyrl"},
				{Lcid.AZ_CYRL_AZ, "az-Cyrl-AZ"},
				{Lcid.AZ_LATN, "az-Latn"},
				{Lcid.AZ_LATN_AZ, "az-Latn-AZ"},
				{Lcid.BE, "be"},
				{Lcid.BE_BY, "be-BY"},
				{Lcid.BG, "bg"},
				{Lcid.BG_BG, "bg-BG"},
				{Lcid.BN, "bn"},
				{Lcid.BN_BD, "bn-BD"},
				{Lcid.BN_IN, "bn-IN"},
				{Lcid.BO, "bo"},
				{Lcid.BO_CN, "bo-CN"},
				{Lcid.BR, "br"},
				{Lcid.BR_FR, "br-FR"},
				{Lcid.BS, "bs"},
				{Lcid.BS_CYRL, "bs-Cyrl"},
				{Lcid.BS_CYRL_BA, "bs-Cyrl-BA"},
				{Lcid.BS_LATN, "bs-Latn"},
				{Lcid.BS_LATN_BA, "bs-Latn-BA"},
				{Lcid.CA, "ca"},
				{Lcid.CA_ES, "ca-ES"},
				{Lcid.CA_ES_VALENCIA, "ca-ES-valencia"},
				{Lcid.CHR, "chr"},
				{Lcid.CS, "cs"},
				{Lcid.CS_CZ, "cs-CZ"},
				{Lcid.CY, "cy"},
				{Lcid.CY_GB, "cy-GB"},
				{Lcid.DA, "da"},
				{Lcid.DA_DK, "da-DK"},
				{Lcid.DE, "de"},
				{Lcid.DE_AT, "de-AT"},
				{Lcid.DE_CH, "de-CH"},
				{Lcid.DE_DE, "de-DE"},
				{Lcid.DE_LI, "de-LI"},
				{Lcid.DE_LU, "de-LU"},
				{Lcid.DSB, "dsb"},
				{Lcid.DSB_DE, "dsb-DE"},
				{Lcid.EL, "el"},
				{Lcid.EL_GR, "el-GR"},
				{Lcid.EN, "en"},
				{Lcid.EN_AU, "en-AU"},
				{Lcid.EN_BZ, "en-BZ"},
				{Lcid.EN_CA, "en-CA"},
				{Lcid.EN_GB, "en-GB"},
				{Lcid.EN_HK, "en-HK"},
				{Lcid.EN_IE, "en-IE"},
				{Lcid.EN_IN, "en-IN"},
				{Lcid.EN_JM, "en-JM"},
				{Lcid.EN_MY, "en-MY"},
				{Lcid.EN_NZ, "en-NZ"},
				{Lcid.EN_PH, "en-PH"},
				{Lcid.EN_SG, "en-SG"},
				{Lcid.EN_TT, "en-TT"},
				{Lcid.EN_US, "en-US"},
				{Lcid.EN_ZA, "en-ZA"},
				{Lcid.EN_ZW, "en-ZW"},
				{Lcid.ES, "es"},
				{Lcid.ES_AR, "es-AR"},
				{Lcid.ES_BO, "es-BO"},
				{Lcid.ES_CL, "es-CL"},
				{Lcid.ES_CO, "es-CO"},
				{Lcid.ES_CR, "es-CR"},
				{Lcid.ES_CU, "es-CU"},
				{Lcid.ES_DO, "es-DO"},
				{Lcid.ES_EC, "es-EC"},
				{Lcid.ES_ES, "es-ES"},
				{Lcid.ES_GT, "es-GT"},
				{Lcid.ES_HN, "es-HN"},
				{Lcid.ES_MX, "es-MX"},
				{Lcid.ES_NI, "es-NI"},
				{Lcid.ES_PA, "es-PA"},
				{Lcid.ES_PE, "es-PE"},
				{Lcid.ES_PR, "es-PR"},
				{Lcid.ES_PY, "es-PY"},
				{Lcid.ES_SV, "es-SV"},
				{Lcid.ES_US, "es-US"},
				{Lcid.ES_UY, "es-UY"},
				{Lcid.ES_VE, "es-VE"},
				{Lcid.ET, "et"},
				{Lcid.ET_EE, "et-EE"},
				{Lcid.EU, "eu"},
				{Lcid.EU_ES, "eu-ES"},
				{Lcid.FA, "fa"},
				{Lcid.FA_IR, "fa-IR"},
				{Lcid.FF, "ff"},
				{Lcid.FI, "fi"},
				{Lcid.FI_FI, "fi-FI"},
				{Lcid.FIL, "fil"},
				{Lcid.FIL_PH, "fil-PH"},
				{Lcid.FO, "fo"},
				{Lcid.FO_FO, "fo-FO"},
				{Lcid.FR, "fr"},
				{Lcid.FR_BE, "fr-BE"},
				{Lcid.FR_CA, "fr-CA"},
				{Lcid.FR_CD, "fr-CD"},
				{Lcid.FR_CH, "fr-CH"},
				{Lcid.FR_CI, "fr-CI"},
				{Lcid.FR_CM, "fr-CM"},
				{Lcid.FR_FR, "fr-FR"},
				{Lcid.FR_HT, "fr-HT"},
				{Lcid.FR_LU, "fr-LU"},
				{Lcid.FR_MA, "fr-MA"},
				{Lcid.FR_MC, "fr-MC"},
				{Lcid.FR_ML, "fr-ML"},
				{Lcid.FR_RE, "fr-RE"},
				{Lcid.FR_SN, "fr-SN"},
				{Lcid.FY, "fy"},
				{Lcid.FY_NL, "fy-NL"},
				{Lcid.GA, "ga"},
				{Lcid.GA_IE, "ga-IE"},
				{Lcid.GD, "gd"},
				{Lcid.GD_GB, "gd-GB"},
				{Lcid.GL, "gl"},
				{Lcid.GL_ES, "gl-ES"},
				{Lcid.GSW, "gsw"},
				{Lcid.GSW_FR, "gsw-FR"},
				{Lcid.GU, "gu"},
				{Lcid.GU_IN, "gu-IN"},
				{Lcid.HA, "ha"},
				{Lcid.HA_LATN, "ha-Latn"},
				{Lcid.HA_LATN_NG, "ha-Latn-NG"},
				{Lcid.HAW, "haw"},
				{Lcid.HAW_US, "haw-US"},
				{Lcid.HE, "he"},
				{Lcid.HE_IL, "he-IL"},
				{Lcid.HI, "hi"},
				{Lcid.HI_IN, "hi-IN"},
				{Lcid.HR_BA, "hr-BA"},
				{Lcid.HR_HR, "hr-HR"},
				{Lcid.HR, "hr"},
				{Lcid.HSB, "hsb"},
				{Lcid.HSB_DE, "hsb-DE"},
				{Lcid.HU, "hu"},
				{Lcid.HU_HU, "hu-HU"},
				{Lcid.HY, "hy"},
				{Lcid.HY_AM, "hy-AM"},
				{Lcid.ID, "id"},
				{Lcid.ID_ID, "id-ID"},
				{Lcid.IG, "ig"},
				{Lcid.IG_NG, "ig-NG"},
				{Lcid.II, "ii"},
				{Lcid.II_CN, "ii-CN"},
				{Lcid.IS, "is"},
				{Lcid.IS_IS, "is-IS"},
				{Lcid.IT, "it"},
				{Lcid.IT_CH, "it-CH"},
				{Lcid.IT_IT, "it-IT"},
				{Lcid.JA, "ja"},
				{Lcid.JA_JP, "ja-JP"},
				{Lcid.KA, "ka"},
				{Lcid.KA_GE, "ka-GE"},
				{Lcid.KK, "kk"},
				{Lcid.KK_KZ, "kk-KZ"},
				{Lcid.KL, "kl"},
				{Lcid.KL_GL, "kl-GL"},
				{Lcid.KM, "km"},
				{Lcid.KM_KH, "km-KH"},
				{Lcid.KN, "kn"},
				{Lcid.KN_IN, "kn-IN"},
				{Lcid.KO, "ko"},
				{Lcid.KO_KR, "ko-KR"},
				{Lcid.KOK, "kok"},
				{Lcid.KOK_IN, "kok-IN"},
				{Lcid.KY, "ky"},
				{Lcid.KY_KG, "ky-KG"},
				{Lcid.LB, "lb"},
				{Lcid.LB_LU, "lb-LU"},
				{Lcid.LO, "lo"},
				{Lcid.LO_LA, "lo-LA"},
				{Lcid.LT, "lt"},
				{Lcid.LT_LT, "lt-LT"},
				{Lcid.LV, "lv"},
				{Lcid.LV_LV, "lv-LV"},
				{Lcid.MK, "mk"},
				{Lcid.MK_MK, "mk-MK"},
				{Lcid.ML, "ml"},
				{Lcid.ML_IN, "ml-IN"},
				{Lcid.MN, "mn"},
				{Lcid.MN_CYRL, "mn-Cyrl"},
				{Lcid.MN_MN, "mn-MN"},
				{Lcid.MR, "mr"},
				{Lcid.MR_IN, "mr-IN"},
				{Lcid.MS, "ms"},
				{Lcid.MS_BN, "ms-BN"},
				{Lcid.MS_MY, "ms-MY"},
				{Lcid.MT, "mt"},
				{Lcid.MT_MT, "mt-MT"},
				{Lcid.MY, "my"},
				{Lcid.MY_MM, "my-MM"},
				{Lcid.NB, "nb"},
				{Lcid.NB_NO, "nb-NO"},
				{Lcid.NE, "ne"},
				{Lcid.NE_IN, "ne-IN"},
				{Lcid.NE_NP, "ne-NP"},
				{Lcid.NL, "nl"},
				{Lcid.NL_BE, "nl-BE"},
				{Lcid.NL_NL, "nl-NL"},
				{Lcid.NN, "nn"},
				{Lcid.NN_NO, "nn-NO"},
				{Lcid.NO, "no"},
				{Lcid.NSO, "nso"},
				{Lcid.NSO_ZA, "nso-ZA"},
				{Lcid.OM, "om"},
				{Lcid.OM_ET, "om-ET"},
				{Lcid.OR, "or"},
				{Lcid.OR_IN, "or-IN"},
				{Lcid.PA, "pa"},
				{Lcid.PA_ARAB, "pa-Arab"},
				{Lcid.PA_ARAB_PK, "pa-Arab-PK"},
				{Lcid.PL, "pl"},
				{Lcid.PL_PL, "pl-PL"},
				{Lcid.PS, "ps"},
				{Lcid.PS_AF, "ps-AF"},
				{Lcid.PT, "pt"},
				{Lcid.PT_BR, "pt-BR"},
				{Lcid.PT_PT, "pt-PT"},
				{Lcid.RM, "rm"},
				{Lcid.RM_CH, "rm-CH"},
				{Lcid.RO, "ro"},
				{Lcid.RO_MD, "ro-MD"},
				{Lcid.RO_RO, "ro-RO"},
				{Lcid.RU, "ru"},
				{Lcid.RU_MD, "ru-MD"},
				{Lcid.RU_RU, "ru-RU"},
				{Lcid.RW, "rw"},
				{Lcid.RW_RW, "rw-RW"},
				{Lcid.SAH, "sah"},
				{Lcid.SAH_RU, "sah-RU"},
				{Lcid.SE, "se"},
				{Lcid.SE_FI, "se-FI"},
				{Lcid.SE_NO, "se-NO"},
				{Lcid.SE_SE, "se-SE"},
				{Lcid.SI, "si"},
				{Lcid.SI_LK, "si-LK"},
				{Lcid.SK, "sk"},
				{Lcid.SK_SK, "sk-SK"},
				{Lcid.SL, "sl"},
				{Lcid.SL_SI, "sl-SI"},
				{Lcid.SMN, "smn"},
				{Lcid.SMN_FI, "smn-FI"},
				{Lcid.SO, "so"},
				{Lcid.SO_SO, "so-SO"},
				{Lcid.SQ, "sq"},
				{Lcid.SQ_AL, "sq-AL"},
				{Lcid.SR, "sr"},
				{Lcid.SR_CYRL, "sr-Cyrl"},
				{Lcid.SR_CYRL_BA, "sr-Cyrl-BA"},
				{Lcid.SR_CYRL_ME, "sr-Cyrl-ME"},
				{Lcid.SR_CYRL_RS, "sr-Cyrl-RS"},
				{Lcid.SR_LATN, "sr-Latn"},
				{Lcid.SR_LATN_BA, "sr-Latn-BA"},
				{Lcid.SR_LATN_ME, "sr-Latn-ME"},
				{Lcid.SR_LATN_RS, "sr-Latn-RS"},
				{Lcid.ST, "st"},
				{Lcid.ST_ZA, "st-ZA"},
				{Lcid.SV, "sv"},
				{Lcid.SV_FI, "sv-FI"},
				{Lcid.SV_SE, "sv-SE"},
				{Lcid.SW, "sw"},
				{Lcid.SW_KE, "sw-KE"},
				{Lcid.TA, "ta"},
				{Lcid.TA_IN, "ta-IN"},
				{Lcid.TA_LK, "ta-LK"},
				{Lcid.TE, "te"},
				{Lcid.TE_IN, "te-IN"},
				{Lcid.TG, "tg"},
				{Lcid.TG_CYRL, "tg-Cyrl"},
				{Lcid.TG_CYRL_TJ, "tg-Cyrl-TJ"},
				{Lcid.TH, "th"},
				{Lcid.TH_TH, "th-TH"},
				{Lcid.TI, "ti"},
				{Lcid.TI_ER, "ti-ER"},
				{Lcid.TI_ET, "ti-ET"},
				{Lcid.TK, "tk"},
				{Lcid.TK_TM, "tk-TM"},
				{Lcid.TN, "tn"},
				{Lcid.TN_BW, "tn-BW"},
				{Lcid.TN_ZA, "tn-ZA"},
				{Lcid.TR, "tr"},
				{Lcid.TR_TR, "tr-TR"},
				{Lcid.TS, "ts"},
				{Lcid.TS_ZA, "ts-ZA"},
				{Lcid.TZM, "tzm"},
				{Lcid.TZM_LATN, "tzm-Latn"},
				{Lcid.UG, "ug"},
				{Lcid.UG_CN, "ug-CN"},
				{Lcid.UK, "uk"},
				{Lcid.UK_UA, "uk-UA"},
				{Lcid.UR, "ur"},
				{Lcid.UR_IN, "ur-IN"},
				{Lcid.UR_PK, "ur-PK"},
				{Lcid.UZ, "uz"},
				{Lcid.UZ_CYRL, "uz-Cyrl"},
				{Lcid.UZ_CYRL_UZ, "uz-Cyrl-UZ"},
				{Lcid.UZ_LATN, "uz-Latn"},
				{Lcid.UZ_LATN_UZ, "uz-Latn-UZ"},
				{Lcid.VI, "vi"},
				{Lcid.VI_VN, "vi-VN"},
				{Lcid.XH, "xh"},
				{Lcid.XH_ZA, "xh-ZA"},
				{Lcid.YO, "yo"},
				{Lcid.YO_NG, "yo-NG"},
				{Lcid.ZH, "zh"},
				{Lcid.ZH_CN, "zh-CN"},
				{Lcid.ZH_HANS, "zh-Hans"},
				{Lcid.ZH_HANT, "zh-Hant"},
				{Lcid.ZH_HK, "zh-HK"},
				{Lcid.ZH_MO, "zh-MO"},
				{Lcid.ZH_SG, "zh-SG"},
				{Lcid.ZH_TW, "zh-TW"},
				{Lcid.ZU, "zu"},
				{Lcid.ZU_ZA, "zu-ZA"},
			};

		/// <summary>
		/// Dictionary of countries for LCID enum members.
		/// </summary>
		private static readonly Dictionary<Lcid, Iso3166> LcidCountries =
			new Dictionary<Lcid, Iso3166>
			{
				{Lcid.NONE, Iso3166.NONE},
				{Lcid.INVARIANT, Iso3166.NONE},
				{Lcid.AF_ZA, Iso3166.ZA},
				{Lcid.AM_ET, Iso3166.ET},
				{Lcid.AR_AE, Iso3166.AE},
				{Lcid.AR_BH, Iso3166.BH},
				{Lcid.AR_DZ, Iso3166.DZ},
				{Lcid.AR_EG, Iso3166.EG},
				{Lcid.AR_IQ, Iso3166.IQ},
				{Lcid.AR_JO, Iso3166.JO},
				{Lcid.AR_KW, Iso3166.KW},
				{Lcid.AR_LB, Iso3166.LB},
				{Lcid.AR_LY, Iso3166.LY},
				{Lcid.AR_MA, Iso3166.MA},
				{Lcid.AR_OM, Iso3166.OM},
				{Lcid.AR_QA, Iso3166.QA},
				{Lcid.AR_SA, Iso3166.SA},
				{Lcid.AR_SY, Iso3166.SY},
				{Lcid.AR_TN, Iso3166.TN},
				{Lcid.AR_YE, Iso3166.YE},
				{Lcid.AS_IN, Iso3166.IN},
				{Lcid.AZ_CYRL_AZ, Iso3166.AZ},
				{Lcid.AZ_LATN_AZ, Iso3166.AZ},
				{Lcid.BE_BY, Iso3166.BY},
				{Lcid.BG_BG, Iso3166.BG},
				{Lcid.BN_BD, Iso3166.BD},
				{Lcid.BN_IN, Iso3166.IN},
				{Lcid.BO_CN, Iso3166.CN},
				{Lcid.BR_FR, Iso3166.FR},
				{Lcid.BS_CYRL_BA, Iso3166.BA},
				{Lcid.BS_LATN_BA, Iso3166.BA},
				{Lcid.CA_ES, Iso3166.ES},
				{Lcid.CA_ES_VALENCIA, Iso3166.ES},
				{Lcid.CS_CZ, Iso3166.CZ},
				{Lcid.CY_GB, Iso3166.GB},
				{Lcid.DA_DK, Iso3166.DK},
				{Lcid.DE_AT, Iso3166.AT},
				{Lcid.DE_CH, Iso3166.CH},
				{Lcid.DE_DE, Iso3166.DE},
				{Lcid.DE_LI, Iso3166.LI},
				{Lcid.DE_LU, Iso3166.LU},
				{Lcid.DSB_DE, Iso3166.DE},
				{Lcid.EL_GR, Iso3166.GR},
				{Lcid.EN_AU, Iso3166.AU},
				{Lcid.EN_BZ, Iso3166.BZ},
				{Lcid.EN_CA, Iso3166.CA},
				{Lcid.EN_GB, Iso3166.GB},
				{Lcid.EN_HK, Iso3166.HK},
				{Lcid.EN_IE, Iso3166.IE},
				{Lcid.EN_IN, Iso3166.IN},
				{Lcid.EN_JM, Iso3166.JM},
				{Lcid.EN_MY, Iso3166.MY},
				{Lcid.EN_NZ, Iso3166.NZ},
				{Lcid.EN_PH, Iso3166.PH},
				{Lcid.EN_SG, Iso3166.SG},
				{Lcid.EN_TT, Iso3166.TT},
				{Lcid.EN_US, Iso3166.US},
				{Lcid.EN_ZA, Iso3166.ZA},
				{Lcid.EN_ZW, Iso3166.ZW},
				{Lcid.ES_AR, Iso3166.AR},
				{Lcid.ES_BO, Iso3166.BO},
				{Lcid.ES_CL, Iso3166.CL},
				{Lcid.ES_CO, Iso3166.CO},
				{Lcid.ES_CR, Iso3166.CR},
				{Lcid.ES_CU, Iso3166.CU},
				{Lcid.ES_DO, Iso3166.DO},
				{Lcid.ES_EC, Iso3166.EC},
				{Lcid.ES_ES, Iso3166.ES},
				{Lcid.ES_GT, Iso3166.GT},
				{Lcid.ES_HN, Iso3166.HN},
				{Lcid.ES_MX, Iso3166.MX},
				{Lcid.ES_NI, Iso3166.NI},
				{Lcid.ES_PA, Iso3166.PA},
				{Lcid.ES_PE, Iso3166.PE},
				{Lcid.ES_PR, Iso3166.PR},
				{Lcid.ES_PY, Iso3166.PY},
				{Lcid.ES_SV, Iso3166.SV},
				{Lcid.ES_US, Iso3166.US},
				{Lcid.ES_UY, Iso3166.UY},
				{Lcid.ES_VE, Iso3166.VE},
				{Lcid.ET_EE, Iso3166.EE},
				{Lcid.EU_ES, Iso3166.ES},
				{Lcid.FA_IR, Iso3166.IR},
				{Lcid.FI_FI, Iso3166.FI},
				{Lcid.FIL_PH, Iso3166.PH},
				{Lcid.FO_FO, Iso3166.FO},
				{Lcid.FR_BE, Iso3166.BE},
				{Lcid.FR_CA, Iso3166.CA},
				{Lcid.FR_CD, Iso3166.CD},
				{Lcid.FR_CH, Iso3166.CH},
				{Lcid.FR_CI, Iso3166.CI},
				{Lcid.FR_CM, Iso3166.CM},
				{Lcid.FR_FR, Iso3166.FR},
				{Lcid.FR_HT, Iso3166.HT},
				{Lcid.FR_LU, Iso3166.LU},
				{Lcid.FR_MA, Iso3166.MA},
				{Lcid.FR_MC, Iso3166.MC},
				{Lcid.FR_ML, Iso3166.ML},
				{Lcid.FR_RE, Iso3166.RE},
				{Lcid.FR_SN, Iso3166.SN},
				{Lcid.FY_NL, Iso3166.NL},
				{Lcid.GA_IE, Iso3166.IE},
				{Lcid.GD_GB, Iso3166.GB},
				{Lcid.GL_ES, Iso3166.ES},
				{Lcid.GSW_FR, Iso3166.FR},
				{Lcid.GU_IN, Iso3166.IN},
				{Lcid.HA_LATN_NG, Iso3166.NG},
				{Lcid.HAW_US, Iso3166.US},
				{Lcid.HE_IL, Iso3166.IL},
				{Lcid.HI_IN, Iso3166.IN},
				{Lcid.HR_BA, Iso3166.BA},
				{Lcid.HR_HR, Iso3166.HR},
				{Lcid.HSB_DE, Iso3166.DE},
				{Lcid.HU_HU, Iso3166.HU},
				{Lcid.HY_AM, Iso3166.AM},
				{Lcid.ID_ID, Iso3166.ID},
				{Lcid.IG_NG, Iso3166.NG},
				{Lcid.II_CN, Iso3166.CN},
				{Lcid.IS_IS, Iso3166.IS},
				{Lcid.IT_CH, Iso3166.CH},
				{Lcid.IT_IT, Iso3166.IT},
				{Lcid.JA_JP, Iso3166.JP},
				{Lcid.KA_GE, Iso3166.GE},
				{Lcid.KK_KZ, Iso3166.KZ},
				{Lcid.KL_GL, Iso3166.GL},
				{Lcid.KM_KH, Iso3166.KH},
				{Lcid.KN_IN, Iso3166.IN},
				{Lcid.KO_KR, Iso3166.KR},
				{Lcid.KOK_IN, Iso3166.IN},
				{Lcid.KY_KG, Iso3166.KG},
				{Lcid.LB_LU, Iso3166.LU},
				{Lcid.LO_LA, Iso3166.LA},
				{Lcid.LT_LT, Iso3166.LT},
				{Lcid.LV_LV, Iso3166.LV},
				{Lcid.MK_MK, Iso3166.MK},
				{Lcid.ML_IN, Iso3166.IN},
				{Lcid.MN_MN, Iso3166.MN},
				{Lcid.MR_IN, Iso3166.IN},
				{Lcid.MS_BN, Iso3166.BN},
				{Lcid.MS_MY, Iso3166.MY},
				{Lcid.MT_MT, Iso3166.MT},
				{Lcid.MY_MM, Iso3166.MM},
				{Lcid.NB_NO, Iso3166.NO},
				{Lcid.NE_IN, Iso3166.IN},
				{Lcid.NE_NP, Iso3166.NP},
				{Lcid.NL_BE, Iso3166.BE},
				{Lcid.NL_NL, Iso3166.NL},
				{Lcid.NN_NO, Iso3166.NO},
				{Lcid.NSO_ZA, Iso3166.ZA},
				{Lcid.OM_ET, Iso3166.ET},
				{Lcid.OR_IN, Iso3166.IN},
				{Lcid.PA_ARAB_PK, Iso3166.PK},
				{Lcid.PL_PL, Iso3166.PL},
				{Lcid.PS_AF, Iso3166.AF},
				{Lcid.PT_BR, Iso3166.BR},
				{Lcid.PT_PT, Iso3166.PT},
				{Lcid.RM_CH, Iso3166.CH},
				{Lcid.RO_MD, Iso3166.MD},
				{Lcid.RO_RO, Iso3166.RO},
				{Lcid.RU_MD, Iso3166.MD},
				{Lcid.RU_RU, Iso3166.RU},
				{Lcid.RW_RW, Iso3166.RW},
				{Lcid.SAH_RU, Iso3166.RU},
				{Lcid.SE_FI, Iso3166.FI},
				{Lcid.SE_NO, Iso3166.NO},
				{Lcid.SE_SE, Iso3166.SE},
				{Lcid.SI_LK, Iso3166.LK},
				{Lcid.SK_SK, Iso3166.SK},
				{Lcid.SL_SI, Iso3166.SI},
				{Lcid.SMN_FI, Iso3166.FI},
				{Lcid.SO_SO, Iso3166.SO},
				{Lcid.SQ_AL, Iso3166.AL},
				{Lcid.SR_CYRL_BA, Iso3166.BA},
				{Lcid.SR_CYRL_ME, Iso3166.ME},
				{Lcid.SR_CYRL_RS, Iso3166.RS},
				{Lcid.SR_LATN_BA, Iso3166.BA},
				{Lcid.SR_LATN_ME, Iso3166.ME},
				{Lcid.SR_LATN_RS, Iso3166.RS},
				{Lcid.ST_ZA, Iso3166.ZA},
				{Lcid.SV_FI, Iso3166.FI},
				{Lcid.SV_SE, Iso3166.SE},
				{Lcid.SW_KE, Iso3166.KE},
				{Lcid.TA_IN, Iso3166.IN},
				{Lcid.TA_LK, Iso3166.LK},
				{Lcid.TE_IN, Iso3166.IN},
				{Lcid.TG_CYRL_TJ, Iso3166.TJ},
				{Lcid.TH_TH, Iso3166.TH},
				{Lcid.TI_ER, Iso3166.ER},
				{Lcid.TI_ET, Iso3166.ET},
				{Lcid.TK_TM, Iso3166.TM},
				{Lcid.TN_BW, Iso3166.BW},
				{Lcid.TN_ZA, Iso3166.ZA},
				{Lcid.TR_TR, Iso3166.TR},
				{Lcid.TS_ZA, Iso3166.ZA},
				{Lcid.UG_CN, Iso3166.CN},
				{Lcid.UK_UA, Iso3166.UA},
				{Lcid.UR_IN, Iso3166.IN},
				{Lcid.UR_PK, Iso3166.PK},
				{Lcid.UZ_CYRL_UZ, Iso3166.UZ},
				{Lcid.UZ_LATN_UZ, Iso3166.UZ},
				{Lcid.VI_VN, Iso3166.VN},
				{Lcid.XH_ZA, Iso3166.ZA},
				{Lcid.YO_NG, Iso3166.NG},
				{Lcid.ZH_CN, Iso3166.CN},
				{Lcid.ZH_HK, Iso3166.HK},
				{Lcid.ZH_MO, Iso3166.MO},
				{Lcid.ZH_SG, Iso3166.SG},
				{Lcid.ZH_TW, Iso3166.TW},
				{Lcid.ZU_ZA, Iso3166.ZA},
			};

		/// <summary>
		/// Dictionary of the regions for enum members.
		/// </summary>
		private static readonly Dictionary<Lcid, Unm49> LcidRegions =
			new Dictionary<Lcid, Unm49>
			{
				{Lcid.NONE, Unm49.NONE},
				{Lcid.INVARIANT, Unm49.NONE},
			};

		/// <summary>
		/// Dictionary of the languages for LCID enum members.
		/// </summary>
		private static readonly Dictionary<Lcid, Iso639> LcidLanguages =
			new Dictionary<Lcid, Iso639>
			{
				{Lcid.NONE, Iso639.NONE},
				{Lcid.INVARIANT, Iso639.NONE},
				{Lcid.AF, Iso639.AF},
				{Lcid.AF_ZA, Iso639.AF},
				{Lcid.AM, Iso639.AM},
				{Lcid.AM_ET, Iso639.AM},
				{Lcid.AR, Iso639.AR},
				{Lcid.AR_AE, Iso639.AR},
				{Lcid.AR_BH, Iso639.AR},
				{Lcid.AR_DZ, Iso639.AR},
				{Lcid.AR_EG, Iso639.AR},
				{Lcid.AR_IQ, Iso639.AR},
				{Lcid.AR_JO, Iso639.AR},
				{Lcid.AR_KW, Iso639.AR},
				{Lcid.AR_LB, Iso639.AR},
				{Lcid.AR_LY, Iso639.AR},
				{Lcid.AR_MA, Iso639.AR},
				{Lcid.AR_OM, Iso639.AR},
				{Lcid.AR_QA, Iso639.AR},
				{Lcid.AR_SA, Iso639.AR},
				{Lcid.AR_SY, Iso639.AR},
				{Lcid.AR_TN, Iso639.AR},
				{Lcid.AR_YE, Iso639.AR},
				{Lcid.AS, Iso639.AS},
				{Lcid.AS_IN, Iso639.AS},
				{Lcid.AZ, Iso639.AZ},
				{Lcid.AZ_CYRL, Iso639.AZ},
				{Lcid.AZ_CYRL_AZ, Iso639.AZ},
				{Lcid.AZ_LATN, Iso639.AZ},
				{Lcid.AZ_LATN_AZ, Iso639.AZ},
				{Lcid.BE, Iso639.BE},
				{Lcid.BE_BY, Iso639.BE},
				{Lcid.BG, Iso639.BG},
				{Lcid.BG_BG, Iso639.BG},
				{Lcid.BN, Iso639.BN},
				{Lcid.BN_BD, Iso639.BN},
				{Lcid.BN_IN, Iso639.BN},
				{Lcid.BO, Iso639.BO},
				{Lcid.BO_CN, Iso639.BO},
				{Lcid.BR, Iso639.BR},
				{Lcid.BR_FR, Iso639.BR},
				{Lcid.BS, Iso639.BS},
				{Lcid.BS_CYRL, Iso639.BS},
				{Lcid.BS_CYRL_BA, Iso639.BS},
				{Lcid.BS_LATN, Iso639.BS},
				{Lcid.BS_LATN_BA, Iso639.BS},
				{Lcid.CA, Iso639.CA},
				{Lcid.CA_ES, Iso639.CA},
				{Lcid.CA_ES_VALENCIA, Iso639.CA},
				{Lcid.CS, Iso639.CS},
				{Lcid.CS_CZ, Iso639.CS},
				{Lcid.CY, Iso639.CY},
				{Lcid.CY_GB, Iso639.CY},
				{Lcid.DA, Iso639.DA},
				{Lcid.DA_DK, Iso639.DA},
				{Lcid.DE, Iso639.DE},
				{Lcid.DE_AT, Iso639.DE},
				{Lcid.DE_CH, Iso639.DE},
				{Lcid.DE_DE, Iso639.DE},
				{Lcid.DE_LI, Iso639.DE},
				{Lcid.DE_LU, Iso639.DE},
				{Lcid.EL, Iso639.EL},
				{Lcid.EL_GR, Iso639.EL},
				{Lcid.EN, Iso639.EN},
				{Lcid.EN_AU, Iso639.EN},
				{Lcid.EN_BZ, Iso639.EN},
				{Lcid.EN_CA, Iso639.EN},
				{Lcid.EN_GB, Iso639.EN},
				{Lcid.EN_HK, Iso639.EN},
				{Lcid.EN_IE, Iso639.EN},
				{Lcid.EN_IN, Iso639.EN},
				{Lcid.EN_JM, Iso639.EN},
				{Lcid.EN_MY, Iso639.EN},
				{Lcid.EN_NZ, Iso639.EN},
				{Lcid.EN_PH, Iso639.EN},
				{Lcid.EN_SG, Iso639.EN},
				{Lcid.EN_TT, Iso639.EN},
				{Lcid.EN_US, Iso639.EN},
				{Lcid.EN_ZA, Iso639.EN},
				{Lcid.EN_ZW, Iso639.EN},
				{Lcid.ES, Iso639.ES},
				{Lcid.ES_AR, Iso639.ES},
				{Lcid.ES_BO, Iso639.ES},
				{Lcid.ES_CL, Iso639.ES},
				{Lcid.ES_CO, Iso639.ES},
				{Lcid.ES_CR, Iso639.ES},
				{Lcid.ES_CU, Iso639.ES},
				{Lcid.ES_DO, Iso639.ES},
				{Lcid.ES_EC, Iso639.ES},
				{Lcid.ES_ES, Iso639.ES},
				{Lcid.ES_GT, Iso639.ES},
				{Lcid.ES_HN, Iso639.ES},
				{Lcid.ES_MX, Iso639.ES},
				{Lcid.ES_NI, Iso639.ES},
				{Lcid.ES_PA, Iso639.ES},
				{Lcid.ES_PE, Iso639.ES},
				{Lcid.ES_PR, Iso639.ES},
				{Lcid.ES_PY, Iso639.ES},
				{Lcid.ES_SV, Iso639.ES},
				{Lcid.ES_US, Iso639.ES},
				{Lcid.ES_UY, Iso639.ES},
				{Lcid.ES_VE, Iso639.ES},
				{Lcid.ET, Iso639.ET},
				{Lcid.ET_EE, Iso639.ET},
				{Lcid.EU, Iso639.EU},
				{Lcid.EU_ES, Iso639.EU},
				{Lcid.FA, Iso639.FA},
				{Lcid.FA_IR, Iso639.FA},
				{Lcid.FF, Iso639.FF},
				{Lcid.FI, Iso639.FI},
				{Lcid.FI_FI, Iso639.FI},
				{Lcid.FO, Iso639.FO},
				{Lcid.FO_FO, Iso639.FO},
				{Lcid.FR, Iso639.FR},
				{Lcid.FR_BE, Iso639.FR},
				{Lcid.FR_CA, Iso639.FR},
				{Lcid.FR_CD, Iso639.FR},
				{Lcid.FR_CH, Iso639.FR},
				{Lcid.FR_CI, Iso639.FR},
				{Lcid.FR_CM, Iso639.FR},
				{Lcid.FR_FR, Iso639.FR},
				{Lcid.FR_HT, Iso639.FR},
				{Lcid.FR_LU, Iso639.FR},
				{Lcid.FR_MA, Iso639.FR},
				{Lcid.FR_MC, Iso639.FR},
				{Lcid.FR_ML, Iso639.FR},
				{Lcid.FR_RE, Iso639.FR},
				{Lcid.FR_SN, Iso639.FR},
				{Lcid.FY, Iso639.FY},
				{Lcid.FY_NL, Iso639.FY},
				{Lcid.GA, Iso639.GA},
				{Lcid.GA_IE, Iso639.GA},
				{Lcid.GD, Iso639.GD},
				{Lcid.GD_GB, Iso639.GD},
				{Lcid.GL, Iso639.GL},
				{Lcid.GL_ES, Iso639.GL},
				{Lcid.GU, Iso639.GU},
				{Lcid.GU_IN, Iso639.GU},
				{Lcid.HA, Iso639.HA},
				{Lcid.HA_LATN, Iso639.HA},
				{Lcid.HA_LATN_NG, Iso639.HA},
				{Lcid.HE, Iso639.HE},
				{Lcid.HE_IL, Iso639.HE},
				{Lcid.HI, Iso639.HI},
				{Lcid.HI_IN, Iso639.HI},
				{Lcid.HR_BA, Iso639.HR},
				{Lcid.HR_HR, Iso639.HR},
				{Lcid.HR, Iso639.HR},
				{Lcid.HU, Iso639.HU},
				{Lcid.HU_HU, Iso639.HU},
				{Lcid.HY, Iso639.HY},
				{Lcid.HY_AM, Iso639.HY},
				{Lcid.ID, Iso639.ID},
				{Lcid.ID_ID, Iso639.ID},
				{Lcid.IG, Iso639.IG},
				{Lcid.IG_NG, Iso639.IG},
				{Lcid.II, Iso639.II},
				{Lcid.II_CN, Iso639.II},
				{Lcid.IS, Iso639.IS},
				{Lcid.IS_IS, Iso639.IS},
				{Lcid.IT, Iso639.IT},
				{Lcid.IT_CH, Iso639.IT},
				{Lcid.IT_IT, Iso639.IT},
				{Lcid.JA, Iso639.JA},
				{Lcid.JA_JP, Iso639.JA},
				{Lcid.KA, Iso639.KA},
				{Lcid.KA_GE, Iso639.KA},
				{Lcid.KK, Iso639.KK},
				{Lcid.KK_KZ, Iso639.KK},
				{Lcid.KL, Iso639.KL},
				{Lcid.KL_GL, Iso639.KL},
				{Lcid.KM, Iso639.KM},
				{Lcid.KM_KH, Iso639.KM},
				{Lcid.KN, Iso639.KN},
				{Lcid.KN_IN, Iso639.KN},
				{Lcid.KO, Iso639.KO},
				{Lcid.KO_KR, Iso639.KO},
				{Lcid.KY, Iso639.KY},
				{Lcid.KY_KG, Iso639.KY},
				{Lcid.LB, Iso639.LB},
				{Lcid.LB_LU, Iso639.LB},
				{Lcid.LO, Iso639.LO},
				{Lcid.LO_LA, Iso639.LO},
				{Lcid.LT, Iso639.LT},
				{Lcid.LT_LT, Iso639.LT},
				{Lcid.LV, Iso639.LV},
				{Lcid.LV_LV, Iso639.LV},
				{Lcid.MK, Iso639.MK},
				{Lcid.MK_MK, Iso639.MK},
				{Lcid.ML, Iso639.ML},
				{Lcid.ML_IN, Iso639.ML},
				{Lcid.MN, Iso639.MN},
				{Lcid.MN_CYRL, Iso639.MN},
				{Lcid.MN_MN, Iso639.MN},
				{Lcid.MR, Iso639.MR},
				{Lcid.MR_IN, Iso639.MR},
				{Lcid.MS, Iso639.MS},
				{Lcid.MS_BN, Iso639.MS},
				{Lcid.MS_MY, Iso639.MS},
				{Lcid.MT, Iso639.MT},
				{Lcid.MT_MT, Iso639.MT},
				{Lcid.MY, Iso639.MY},
				{Lcid.MY_MM, Iso639.MY},
				{Lcid.NB, Iso639.NB},
				{Lcid.NB_NO, Iso639.NB},
				{Lcid.NE, Iso639.NE},
				{Lcid.NE_IN, Iso639.NE},
				{Lcid.NE_NP, Iso639.NE},
				{Lcid.NL, Iso639.NL},
				{Lcid.NL_BE, Iso639.NL},
				{Lcid.NL_NL, Iso639.NL},
				{Lcid.NN, Iso639.NN},
				{Lcid.NN_NO, Iso639.NN},
				{Lcid.NO, Iso639.NO},
				{Lcid.OM, Iso639.OM},
				{Lcid.OM_ET, Iso639.OM},
				{Lcid.OR, Iso639.OR},
				{Lcid.OR_IN, Iso639.OR},
				{Lcid.PA, Iso639.PA},
				{Lcid.PA_ARAB, Iso639.PA},
				{Lcid.PA_ARAB_PK, Iso639.PA},
				{Lcid.PL, Iso639.PL},
				{Lcid.PL_PL, Iso639.PL},
				{Lcid.PS, Iso639.PS},
				{Lcid.PS_AF, Iso639.PS},
				{Lcid.PT, Iso639.PT},
				{Lcid.PT_BR, Iso639.PT},
				{Lcid.PT_PT, Iso639.PT},
				{Lcid.RM, Iso639.RM},
				{Lcid.RM_CH, Iso639.RM},
				{Lcid.RO, Iso639.RO},
				{Lcid.RO_MD, Iso639.RO},
				{Lcid.RO_RO, Iso639.RO},
				{Lcid.RU, Iso639.RU},
				{Lcid.RU_MD, Iso639.RU},
				{Lcid.RU_RU, Iso639.RU},
				{Lcid.RW, Iso639.RW},
				{Lcid.RW_RW, Iso639.RW},
				{Lcid.SE, Iso639.SE},
				{Lcid.SE_FI, Iso639.SE},
				{Lcid.SE_NO, Iso639.SE},
				{Lcid.SE_SE, Iso639.SE},
				{Lcid.SI, Iso639.SI},
				{Lcid.SI_LK, Iso639.SI},
				{Lcid.SK, Iso639.SK},
				{Lcid.SK_SK, Iso639.SK},
				{Lcid.SL, Iso639.SL},
				{Lcid.SL_SI, Iso639.SL},
				{Lcid.SO, Iso639.SO},
				{Lcid.SO_SO, Iso639.SO},
				{Lcid.SQ, Iso639.SQ},
				{Lcid.SQ_AL, Iso639.SQ},
				{Lcid.SR, Iso639.SR},
				{Lcid.SR_CYRL, Iso639.SR},
				{Lcid.SR_CYRL_BA, Iso639.SR},
				{Lcid.SR_CYRL_ME, Iso639.SR},
				{Lcid.SR_CYRL_RS, Iso639.SR},
				{Lcid.SR_LATN, Iso639.SR},
				{Lcid.SR_LATN_BA, Iso639.SR},
				{Lcid.SR_LATN_ME, Iso639.SR},
				{Lcid.SR_LATN_RS, Iso639.SR},
				{Lcid.ST, Iso639.ST},
				{Lcid.ST_ZA, Iso639.ST},
				{Lcid.SV, Iso639.SV},
				{Lcid.SV_FI, Iso639.SV},
				{Lcid.SV_SE, Iso639.SV},
				{Lcid.SW, Iso639.SW},
				{Lcid.SW_KE, Iso639.SW},
				{Lcid.TA, Iso639.TA},
				{Lcid.TA_IN, Iso639.TA},
				{Lcid.TA_LK, Iso639.TA},
				{Lcid.TE, Iso639.TE},
				{Lcid.TE_IN, Iso639.TE},
				{Lcid.TG, Iso639.TG},
				{Lcid.TG_CYRL, Iso639.TG},
				{Lcid.TG_CYRL_TJ, Iso639.TG},
				{Lcid.TH, Iso639.TH},
				{Lcid.TH_TH, Iso639.TH},
				{Lcid.TI, Iso639.TI},
				{Lcid.TI_ER, Iso639.TI},
				{Lcid.TI_ET, Iso639.TI},
				{Lcid.TK, Iso639.TK},
				{Lcid.TK_TM, Iso639.TK},
				{Lcid.TN, Iso639.TN},
				{Lcid.TN_BW, Iso639.TN},
				{Lcid.TN_ZA, Iso639.TN},
				{Lcid.TR, Iso639.TR},
				{Lcid.TR_TR, Iso639.TR},
				{Lcid.TS, Iso639.TS},
				{Lcid.TS_ZA, Iso639.TS},
				{Lcid.UG, Iso639.UG},
				{Lcid.UG_CN, Iso639.UG},
				{Lcid.UK, Iso639.UK},
				{Lcid.UK_UA, Iso639.UK},
				{Lcid.UR, Iso639.UR},
				{Lcid.UR_IN, Iso639.UR},
				{Lcid.UR_PK, Iso639.UR},
				{Lcid.UZ, Iso639.UZ},
				{Lcid.UZ_CYRL, Iso639.UZ},
				{Lcid.UZ_CYRL_UZ, Iso639.UZ},
				{Lcid.UZ_LATN, Iso639.UZ},
				{Lcid.UZ_LATN_UZ, Iso639.UZ},
				{Lcid.VI, Iso639.VI},
				{Lcid.VI_VN, Iso639.VI},
				{Lcid.XH, Iso639.XH},
				{Lcid.XH_ZA, Iso639.XH},
				{Lcid.YO, Iso639.YO},
				{Lcid.YO_NG, Iso639.YO},
				{Lcid.ZH, Iso639.ZH},
				{Lcid.ZH_CN, Iso639.ZH},
				{Lcid.ZH_HANS, Iso639.ZH},
				{Lcid.ZH_HANT, Iso639.ZH},
				{Lcid.ZH_HK, Iso639.ZH},
				{Lcid.ZH_MO, Iso639.ZH},
				{Lcid.ZH_SG, Iso639.ZH},
				{Lcid.ZH_TW, Iso639.ZH},
				{Lcid.ZU, Iso639.ZU},
				{Lcid.ZU_ZA, Iso639.ZU},
			};

		/// <summary>
		/// Dictionary of aliases of LCID enum members.
		/// </summary>
		private static readonly Dictionary<string, Lcid> LcidAliases =
			new Dictionary<string, Lcid>
			{
				{"zh-CHS", Lcid.ZH_HANS},
				{"zh-CHT", Lcid.ZH_HANT},
			};
	}
}